/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.complementarios;

import static java.lang.Boolean.TRUE;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rick
 */
public class Ejercicio5 extends javax.swing.JInternalFrame {

    DefaultTableModel dftm;
    /**
     * Creates new form Ejercicio5
     */
    public Ejercicio5() {
        initComponents();
        Object[][] datos = {
            {String.valueOf("Ricardo"), String.valueOf("Castaneda"),
                String.valueOf("Golf"), Integer.parseInt("10"), TRUE},
            {String.valueOf("Jose"), String.valueOf("Hernandez"),
                String.valueOf("Swimming"), Integer.parseInt("3"), TRUE}
        };
        
        String[] columnas = {"Nombre", "Apellido", "Pasatiempo", "Años de practica", "Soltero(a)"};

        dftm = new DefaultTableModel(datos, columnas);
        jTableDemo.setModel(dftm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDemo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Guia 5 - Ejercicio 5");

        jTableDemo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDemo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDemoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDemo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDemoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDemoMouseClicked
        // TODO add your handling code here:
        int fila = jTableDemo.rowAtPoint(evt.getPoint());
        int columna = jTableDemo.columnAtPoint(evt.getPoint());
        if ((fila > -1) && (columna > -1)) {
            JOptionPane.showMessageDialog(null, "Valor seleccionado: \n" + dftm.getValueAt(fila,columna));

        }
    }//GEN-LAST:event_jTableDemoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDemo;
    // End of variables declaration//GEN-END:variables
}
