/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.complementarios;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import sv.edu.udb.desarrollo.FrameUtils;

/**
 *
 * @author Rick
 */
public class InternalFrameMostrarImagenes extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameMostrarImagenes
     */
    public InternalFrameMostrarImagenes() {
        initComponents();
        buttonGroup1.add(rbtEstrella);
        buttonGroup1.add(rbtGalaxia);
        buttonGroup1.add(rbtNebulosa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbtEstrella = new javax.swing.JRadioButton();
        rbtGalaxia = new javax.swing.JRadioButton();
        rbtNebulosa = new javax.swing.JRadioButton();
        lblImagen = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Internal Frame - Mostrar Imagenes");

        rbtEstrella.setText("Estrella");
        rbtEstrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEstrellaActionPerformed(evt);
            }
        });

        rbtGalaxia.setText("Galaxia");
        rbtGalaxia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGalaxiaActionPerformed(evt);
            }
        });

        rbtNebulosa.setText("Nebulosa");
        rbtNebulosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNebulosaActionPerformed(evt);
            }
        });

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setText("Vista Previa Imagen");
        lblImagen.setToolTipText("");

        lblTitulo.setText("Seleccionar una imagen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtNebulosa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtGalaxia, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtEstrella, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtEstrella)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtGalaxia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtNebulosa))
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtEstrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEstrellaActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/sv/edu/udb/desarrollo/img/estrella.jpg"));
        lblImagen.setIcon((Icon) FrameUtils.getScaledImage(icon.getImage(), 275, 250));
        lblImagen.setText("");
    }//GEN-LAST:event_rbtEstrellaActionPerformed

    private void rbtGalaxiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGalaxiaActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/sv/edu/udb/desarrollo/img/galaxia.png"));
        lblImagen.setIcon((Icon) FrameUtils.getScaledImage(icon.getImage(), 275, 250));
        lblImagen.setText("");
    }//GEN-LAST:event_rbtGalaxiaActionPerformed

    private void rbtNebulosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNebulosaActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/sv/edu/udb/desarrollo/img/nebulosa.jpg"));
        lblImagen.setIcon((Icon) FrameUtils.getScaledImage(icon.getImage(), 275, 250));
        lblImagen.setText("");
    }//GEN-LAST:event_rbtNebulosaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtEstrella;
    private javax.swing.JRadioButton rbtGalaxia;
    private javax.swing.JRadioButton rbtNebulosa;
    // End of variables declaration//GEN-END:variables
}
