/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.complementarios;

import static java.lang.Boolean.TRUE;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.utils.Conexion;

/**
 *
 * @author Rick
 */
public class DataAlumnos extends javax.swing.JInternalFrame {

    DefaultTableModel dftm;

    /**
     * Creates new form ListarTablas
     */
    public DataAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();
        lblTablaAlumnos = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("UDB 2020");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jTableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlumnos);

        lblTablaAlumnos.setText("Tabla - Alumnos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblTablaAlumnos)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTablaAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Conexion con = null;
        try {
            con = new Conexion();
        } catch (SQLException ex) {
            Logger.getLogger(DataAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql = "SELECT * FROM alumno";

        con.setRs(sql);
        ResultSet rs = con.getRs();
        try {

            Object[][] datos = new Object[10][5];
            while (rs.next()) {
                datos[rs.getRow() - 1][0] = rs.getInt(1);
                datos[rs.getRow() - 1][1] = rs.getString(2);
                datos[rs.getRow() - 1][2] = rs.getString(3);
                datos[rs.getRow() - 1][3] = rs.getInt(4);
                datos[rs.getRow() - 1][4] = rs.getString(5);

            }

            String[] columnas = {"Id", "Nombre", "Apellido", "Edad", "Direccion"};

            dftm = new DefaultTableModel(datos, columnas);
            jTableAlumnos.setModel(dftm);
        } catch (SQLException ex) {
            Logger.getLogger(DataAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            con.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(DataAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jTableAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlumnosMouseClicked
        int rowNumber = jTableAlumnos.getSelectedRow();
        String idAlumno = jTableAlumnos.getValueAt(rowNumber, 0).toString();

        Conexion con = null;
        try {
            con = new Conexion();
            String sql = "DELETE FROM Alumnos WHERE Cod_alumno = " + idAlumno + " ;";
            con.setRs(sql);
            ResultSet rs = con.getRs();

            Object[][] datos = new Object[10][5];
            while (rs.next()) {
                datos[rs.getRow() - 1][0] = rs.getInt(1);
                datos[rs.getRow() - 1][1] = rs.getInt(2);
                datos[rs.getRow() - 1][2] = rs.getString(3);
                datos[rs.getRow() - 1][3] = rs.getString(4);

            }

            String[] columnas = {"Cod_Alumno", "Cod_Materia", "Nombre", "Descripcion"};

            dftm = new DefaultTableModel(datos, columnas);
            //jTable1.setModel(dftm);
        } catch (SQLException ex) {
            Logger.getLogger(DataAlumnos.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }//GEN-LAST:event_jTableAlumnosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlumnos;
    private javax.swing.JLabel lblTablaAlumnos;
    // End of variables declaration//GEN-END:variables
}
