/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.complementarios;

/**
 *
 * @author Rick
 */
public class DBMidi extends javax.swing.JFrame {

    /**
     * Creates new form DBMidi
     */
    public DBMidi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        tablasMenu = new javax.swing.JMenu();
        alumnosMenuItem = new javax.swing.JMenuItem();
        materiaMenuItem = new javax.swing.JMenuItem();
        joinTableMenuItem = new javax.swing.JMenuItem();
        consultasMenu = new javax.swing.JMenu();
        selectMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablasMenu.setMnemonic('f');
        tablasMenu.setText("Tablas");

        alumnosMenuItem.setMnemonic('o');
        alumnosMenuItem.setText("Alumnos");
        alumnosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnosMenuItemActionPerformed(evt);
            }
        });
        tablasMenu.add(alumnosMenuItem);

        materiaMenuItem.setMnemonic('s');
        materiaMenuItem.setText("Materia");
        materiaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaMenuItemActionPerformed(evt);
            }
        });
        tablasMenu.add(materiaMenuItem);

        joinTableMenuItem.setMnemonic('a');
        joinTableMenuItem.setText("Join Table");
        joinTableMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinTableMenuItemActionPerformed(evt);
            }
        });
        tablasMenu.add(joinTableMenuItem);

        menuBar.add(tablasMenu);

        consultasMenu.setMnemonic('e');
        consultasMenu.setText("Consultas");

        selectMenuItem.setMnemonic('t');
        selectMenuItem.setText("Select");
        selectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMenuItemActionPerformed(evt);
            }
        });
        consultasMenu.add(selectMenuItem);

        menuBar.add(consultasMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alumnosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnosMenuItemActionPerformed
        DataAlumnos alumnos = new DataAlumnos();
        desktopPane.add(alumnos);
        alumnos.show();
    }//GEN-LAST:event_alumnosMenuItemActionPerformed

    private void materiaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaMenuItemActionPerformed
        DataMaterias materias = new DataMaterias();
        desktopPane.add(materias);
        materias.show();
    }//GEN-LAST:event_materiaMenuItemActionPerformed

    private void joinTableMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinTableMenuItemActionPerformed
        DataJoinTable jtable = new DataJoinTable();
        desktopPane.add(jtable);
        jtable.show();
    }//GEN-LAST:event_joinTableMenuItemActionPerformed

    private void selectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMenuItemActionPerformed
        // TODO add your handling code here:
        ConsultaSelectInternalFrame select = new ConsultaSelectInternalFrame();
        desktopPane.add(select);
        select.show();
    }//GEN-LAST:event_selectMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBMidi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBMidi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBMidi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBMidi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBMidi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem alumnosMenuItem;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem joinTableMenuItem;
    private javax.swing.JMenuItem materiaMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem selectMenuItem;
    private javax.swing.JMenu tablasMenu;
    // End of variables declaration//GEN-END:variables

}
